// packages/ui-components-svelte/src/lib/components/layout/footer.svelte
<script lang="ts">
	// Copyright 2024 IOTA Stiftung.
	// SPDX-License-Identifier: Apache-2.0.
	import { Footer } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		children?: Snippet;
		class?: string;
	}

	let props: Props = $props();
</script>

<Footer {...props}>
	{@render props.children?.()}
</Footer>

// packages/ui-components-react/src/footer/footer.tsx
// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
import { Footer as FlowbiteFooter } from "flowbite-react";
import { memo, type JSX } from "react";
import type { FooterProps } from "./footerProps";

/**
 * Footer component.
 */
export const Footer = memo(
	({ body }: FooterProps): JSX.Element => <FlowbiteFooter container>{body}</FlowbiteFooter>
);

Footer.displayName = "Footer";
