// packages/ui-components-svelte/src/lib/components/typography/label.svelte
<script lang="ts">
	// Copyright 2024 IOTA Stiftung.
	// SPDX-License-Identifier: Apache-2.0.
	import { Label } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		class?: string;
		children?: Snippet;
	}

	let props: Props = $props();
</script>

<Label
	{...props}
	class={`text-primary dark:text-primary-dark flex flex-col gap-1 text-sm font-medium ${props.class ?? ''}`}
>
	{@render props.children?.()}
</Label>

// packages/ui-components-react/src/label/label.tsx
// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
import { Label as FlowbiteLabel } from "flowbite-react";
import { memo, type JSX } from "react";
import type { LabelProps } from "./labelProps";

/**
 * Label component.
 */
export const Label = memo(({ children, ...rest }: LabelProps): JSX.Element => (
	<FlowbiteLabel {...rest}>{children}</FlowbiteLabel>
));

Label.displayName = "Label";
